#!/usr/bin/env python3
"""Under the Scope — podcast workshop.

Feed it a thought, get an upload-ready episode plus three reels. Voices are
generated by hand in CloneVoice, so the run splits into two commands:

    # 1. write the script and export segments for CloneVoice
    python workshop.py "your episode idea" --to voiceprep

    # ...generate the six voices in CloneVoice, save them into audio/...

    # 2. finish everything from the audio onward
    python workshop.py --project output/<slug> --from assemble

Run a single stage:  python workshop.py --project output/<slug> --only reels

Stages: script → voiceprep →[CloneVoice]→ assemble → transcribe → captions →
        reels → images → video → package
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from workshop import stages
from workshop.config import Config, log, require_ffmpeg, slugify
from workshop.project import Project

BASE = Path(__file__).resolve().parent / "output"


def main() -> None:
    p = argparse.ArgumentParser(description="Under the Scope podcast workshop")
    p.add_argument("idea", nargs="?", help="the thought to build an episode from")
    p.add_argument("--project", help="path to an existing output/<slug> folder")
    p.add_argument("--only", choices=stages.ALL, help="run just one stage")
    p.add_argument("--from", dest="from_stage", choices=stages.ALL,
                   help="start from this stage and run to the end")
    p.add_argument("--to", dest="to_stage", choices=stages.ALL,
                   help="stop after this stage")
    args = p.parse_args()

    cfg = Config.load()
    project = _resolve_project(args)
    to_run = _which_stages(args)

    if any(s not in stages.NO_FFMPEG for s in to_run):
        require_ffmpeg()

    log("workshop", f"episode '{project.data.get('slug')}' — running: {', '.join(to_run)}")
    for name in to_run:
        getattr(stages, name).run(project, cfg)

    if to_run and to_run[-1] == "voiceprep":
        print(f"\n  Now generate the 6 voices in CloneVoice — see "
              f"{project.root/'voice'/'GENERATE_VOICES.md'}\n"
              f"  Then: python workshop.py --project {project.root} --from assemble\n")
    elif "package" in to_run:
        print(f"\n  Done. Upload bundle: {project.upload_dir}\n")


def _resolve_project(args) -> Project:
    if args.project:
        return Project.open(Path(args.project))
    if not args.idea:
        sys.exit("Give me an idea:  python workshop.py \"your episode idea\" --to voiceprep")
    slug = slugify(args.idea.split("—")[0].split(" - ")[0])
    return Project.create(BASE, slug, args.idea)


def _which_stages(args) -> list[str]:
    if args.only:
        return [args.only]
    start = stages.ALL.index(args.from_stage) if args.from_stage else 0
    end = stages.ALL.index(args.to_stage) + 1 if args.to_stage else len(stages.ALL)
    return stages.ALL[start:end]


if __name__ == "__main__":
    main()
