"""Stage 2 — Voice prep (manual voices in CloneVoice).

The voices are generated by hand in CloneVoice, so this stage doesn't call any
API. It gets everything ready for you:

  voice/01_hook.txt … voice/06_outro.txt   <- paste each into CloneVoice
  voice/GENERATE_VOICES.md                  <- step-by-step + where to save files

You generate each segment in CloneVoice and save the audio back into the
project's audio/ folder using the exact filenames listed in the instructions.
The next stage (assemble) picks them up automatically.
"""

from __future__ import annotations

from ..config import SEGMENT_LABELS, SEGMENTS, Config, log
from ..project import Project


def run(project: Project, cfg: Config) -> None:
    episode = project.data.get("episode")
    if not episode:
        raise RuntimeError("No script yet — run the script stage first.")

    voice_dir = project.root / "voice"
    voice_dir.mkdir(exist_ok=True)
    segments = episode["segments"]

    rows = []
    for i, seg in enumerate(SEGMENTS, start=1):
        stem = f"{i:02d}_{seg}"
        (voice_dir / f"{stem}.txt").write_text(segments[seg].strip() + "\n")
        rows.append((stem, seg))

    _write_instructions(voice_dir, rows, project)
    project.mark_done("voiceprep")
    log("voiceprep", f"exported {len(rows)} segment scripts → {voice_dir}")
    log("voiceprep", "generate each in CloneVoice, then run: "
                     f"python workshop.py --project {project.root} --from assemble")


def _write_instructions(voice_dir, rows, project: Project) -> None:
    stats = project.data["episode"].get("segment_stats", {})
    lines = [
        f"# Generate Voices — {project.data['episode']['title']}",
        "",
        "Generate each segment in **CloneVoice**, then save the audio into this",
        f"project's `audio/` folder with the EXACT filename shown below.",
        "",
        "| # | Segment | Size | Paste this script | Save the audio as |",
        "|---|---------|------|-------------------|-------------------|",
    ]
    for stem, seg in rows:
        label = SEGMENT_LABELS[seg]
        s = stats.get(seg, {})
        size = f"{s['words']}w ~{s['est_seconds']/60:.1f}m" if s else "—"
        lines.append(
            f"| {stem[:2]} | {label} | {size} | `voice/{stem}.txt` | `audio/{stem}.mp3` |"
        )
    lines += [
        "",
        "When all six files are in `audio/`, continue the pipeline:",
        "",
        "```",
        f"python workshop.py --project {project.root} --from assemble",
        "```",
        "",
        "Tips:",
        "- Keep the same voice/settings across all six for a consistent sound.",
        "- mp3 or wav both work; if wav, change the extension in the filename.",
    ]
    (voice_dir / "GENERATE_VOICES.md").write_text("\n".join(lines) + "\n")
